DROP TABLE IF EXISTS blogs CASCADE;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE blogs
(
    id UUID PRIMARY KEY         DEFAULT uuid_generate_v4(),
    title    VARCHAR(512)  NOT NULL CHECK ( title <> '' ),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);