definitions:
  models.Blog:
    properties:
      created_at:
        type: string
      id:
        type: string
      title:
        minLength: 3
        type: string
    required:
    - title
    type: object
  models.BlogSwagger:
    properties:
      title:
        minLength: 3
        type: string
    required:
    - title
    type: object
  models.BlogsList:
    properties:
      blogs:
        items:
          $ref: '#/definitions/models.Blog'
        type: array
      has_more:
        type: boolean
      page:
        type: integer
      size:
        type: integer
      total_count:
        type: integer
      total_pages:
        type: integer
    type: object
  models.News:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      photo:
        type: string
      published_by:
        type: string
      title:
        minLength: 3
        type: string
    required:
    - title
    type: object
  models.NewsList:
    properties:
      has_more:
        type: boolean
      news:
        items:
          $ref: '#/definitions/models.News'
        type: array
      page:
        type: integer
      size:
        type: integer
      total_count:
        type: integer
      total_pages:
        type: integer
    type: object
  models.NewsSwagger:
    properties:
      description:
        type: string
      photo:
        type: string
      published_by:
        type: string
      title:
        minLength: 3
        type: string
    required:
    - title
    type: object
info:
  contact: {}
paths:
  /blogs:
    post:
      consumes:
      - application/json
      description: create new blog
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.BlogSwagger'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Blog'
        "500":
          description: Internal Server Error
          schema: {}
      summary: CreateBlog new blog
      tags:
      - Blog
  /blogs/{id}:
    delete:
      consumes:
      - application/json
      description: delete blog
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete blog
      tags:
      - Blog
    get:
      consumes:
      - application/json
      description: Get blog by id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Blog'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get blog
      tags:
      - Blog
    put:
      consumes:
      - application/json
      description: update new blog
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.BlogSwagger'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BlogSwagger'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update blog
      tags:
      - Blog
  /blogs/list:
    get:
      consumes:
      - application/json
      description: Get all blog
      parameters:
      - description: title
        in: query
        name: title
        type: string
      - description: page number
        format: page
        in: query
        name: page
        type: integer
      - description: number of elements per page
        format: size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BlogsList'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get Blog
      tags:
      - Blog
  /news:
    post:
      consumes:
      - application/json
      description: CreateNews new news
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.NewsSwagger'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.News'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create new news
      tags:
      - News
  /news/{id}:
    delete:
      consumes:
      - application/json
      description: delete news
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete news
      tags:
      - News
    get:
      consumes:
      - application/json
      description: Get news by id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.News'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get news
      tags:
      - News
    put:
      consumes:
      - application/json
      description: update news
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.NewsSwagger'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.NewsSwagger'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update news
      tags:
      - News
  /news/list:
    get:
      consumes:
      - application/json
      description: Get all news
      parameters:
      - description: title
        in: query
        name: title
        type: string
      - description: page number
        format: page
        in: query
        name: page
        type: integer
      - description: number of elements per page
        format: size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.NewsList'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get News
      tags:
      - News
  /news/soft/{id}:
    delete:
      consumes:
      - application/json
      description: soft delete news
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Soft Delete news
      tags:
      - News
swagger: "2.0"
